"""folowers

Revision ID: 42151d3b30d3
Revises: 42458c3e40b9
Create Date: 2018-07-30 16:22:05.951658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42151d3b30d3'
down_revision = '42458c3e40b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
