"""new fields

Revision ID: 42458c3e40b9
Revises: df591743052a
Create Date: 2018-07-30 13:50:03.152754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42458c3e40b9'
down_revision = 'df591743052a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
